name: CICD pipeline
on: push
jobs: 
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Printing a message
              run: echo "Hello, World!"
            - name: Show current time
              run: date
            - name: List files in the repository
              run: ls -la
                

